import 'package:doordash_drive_api/doordash_drive_api.dart';
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'delivery_item.g.dart';

@JsonSerializable()
class DeliveryItem extends Equatable {
  const DeliveryItem({
    required this.name,
    required this.quantity,
    this.description,
    this.externalId,
    this.externalInstanceId,
    this.volume,
    this.weight,
    this.length,
    this.width,
    this.height,
    this.price,
    this.barcode,
    this.itemOptions,
  });

  /// Converts a [Map]<[String], [dynamic]> to a [DeliveryItem]
  factory DeliveryItem.fromJson(Map<String, dynamic> json) =>
      _$DeliveryItemFromJson(json);

  /// Converts a [DeliveryItem] to a [Map]<[String], [dynamic]>
  Map<String, dynamic> toJson() => _$DeliveryItemToJson(this);

  /// Name of the item being delivered.
  final String name;

  /// Description of the item being delivered.
  final String? description;

  /// Quantity of the item being delivered.
  final int quantity;

  /// Unique ID generated by the caller for the item.
  final String? externalId;

  /// Used to distinguish between multiple items with the same external_id, such
  /// as for 2 steaks in the same order with separate weights. Not updatable.
  ///
  // TODO(3ettilina): Verify with Doordash the value coming is an int.
  // Their API says it's String, but the value returned in the json example is
  // an int.
  final int? externalInstanceId;

  /// Unit volume of 1 instance of this item, in cubic feet, with or without a
  /// decimal point. The overall volume of this item is calculated by
  /// multiplying this field by quantity.
  final double? volume;

  /// Unit weight of 1 instance of this item, in pounds (lbs), with or without a
  /// decimal point. The overall weight of this item is calculated by
  /// multiplying this field by quantity.
  final double? weight;

  /// Unit length of 1 instance of this item, in inches, with or without a
  /// decimal point.
  final double? length;

  /// Unit weight of 1 instance of this item, in inches, with or without a
  /// decimal point.
  final double? width;

  /// Unit weight of 1 instance of this item, in inches, with or without a
  /// decimal point.
  final double? height;

  /// Unit price of 1 instance of this item in the lowest currency denomination
  /// (e.g. cents). i.e. $5.99 = 599. The overall price of this item is
  /// calculated by multiplying this field by quantity.
  final int? price;

  /// Barcode identifying the item. This value must be in one of the following
  /// formats: Data Matrix, AZTEC, Code 128, Code 39, Code 93, CODABAR, EAN 13,
  /// EAN 8, ITF, UPC A, UPC E, PDF417. Not updatable.
  ///
  // TODO(3ettilina): Verify with Doordash the value coming is an int.
  // Their API says it's String, but the value returned in the json example
  // is an int.
  final int? barcode;

  /// Details about how to shop for an item. Not updatable.
  final DeliveryItemOptions? itemOptions;

  @override
  List<Object?> get props {
    return [
      name,
      description,
      quantity,
      externalId,
      externalInstanceId,
      volume,
      weight,
      length,
      width,
      height,
      price,
      barcode,
      itemOptions,
    ];
  }
}
